version: "2.2"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER:root
      - MYSQL_PASSWORD:root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=alaadb
    volumes:
      - db_vol:/var/lib/mysqldb

  departement_app:
    build: ./
    image: alaakilani-5win-g2
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on:
      - mysqldb


volumes:
  db_vol: {}